-- Loom Movies Database Schema Setup Script
-- Copy this script and paste it into the Supabase SQL Editor, then click "Run" to create your tables.

-- Enable Row Level Security (RLS) helpers if needed
-- 1. Create Watchlist Table
CREATE TABLE IF NOT EXISTS watchlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL, -- References auth.users(id)
  media_id INT NOT NULL,
  media_type VARCHAR(20) NOT NULL DEFAULT 'movie',
  title VARCHAR(255),
  poster_path VARCHAR(255),
  backdrop_path VARCHAR(255),
  rating NUMERIC(3, 1),
  release_date VARCHAR(20),
  added_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Indexing for fast lookups by user
CREATE INDEX IF NOT EXISTS watchlist_user_idx ON watchlist (user_id);
-- Unique constraint to prevent duplicate watchlists items per user
ALTER TABLE watchlist ADD CONSTRAINT watchlist_user_media_uniq UNIQUE (user_id, media_id, media_type);

-- 2. Create Watch History Table
CREATE TABLE IF NOT EXISTS watch_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL, -- References auth.users(id)
  media_id INT NOT NULL,
  media_type VARCHAR(20) NOT NULL DEFAULT 'movie',
  title VARCHAR(255),
  poster_path VARCHAR(255),
  backdrop_path VARCHAR(255),
  progress INT DEFAULT 0, -- Watched duration in seconds or percentages
  duration INT DEFAULT 0, -- Total episode duration
  watched_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Indexing for fast history retrieval
CREATE INDEX IF NOT EXISTS watch_history_user_idx ON watch_history (user_id);
ALTER TABLE watch_history ADD CONSTRAINT watch_history_user_media_uniq UNIQUE (user_id, media_id, media_type);

-- 3. Setup Row Level Security (RLS) policies
-- This ensures users can only read and write their OWN watchlists and history.
ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_history ENABLE ROW LEVEL SECURITY;

-- Watchlist Policies
CREATE POLICY "Users can view their own watchlist" 
  ON watchlist FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own watchlist items" 
  ON watchlist FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own watchlist items" 
  ON watchlist FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own watchlist items" 
  ON watchlist FOR DELETE 
  USING (auth.uid() = user_id);

-- Watch History Policies
CREATE POLICY "Users can view their own watch history" 
  ON watch_history FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own watch history items" 
  ON watch_history FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own watch history items" 
  ON watch_history FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own watch history items" 
  ON watch_history FOR DELETE 
  USING (auth.uid() = user_id);
